//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace portfolyo2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbAcunMedyaProjectEntities : DbContext
    {
        public DbAcunMedyaProjectEntities()
            : base("name=DbAcunMedyaProjectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_about> tbl_about { get; set; }
        public virtual DbSet<tbl_category> tbl_category { get; set; }
        public virtual DbSet<tbl_contact> tbl_contact { get; set; }
        public virtual DbSet<tbl_education> tbl_education { get; set; }
        public virtual DbSet<tbl_message> tbl_message { get; set; }
        public virtual DbSet<tbl_project> tbl_project { get; set; }
        public virtual DbSet<tbl_services> tbl_services { get; set; }
        public virtual DbSet<tbl_slider> tbl_slider { get; set; }
        public virtual DbSet<tbl_testimonials> testimonials { get; set; }
        public virtual DbSet<tbl_skilss11> tbl_skilss11 { get; set; }
        public virtual DbSet<tbl_Job> tbl_Jobs { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
