//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace portfolyo2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_skilss11
    {
        public int SkillsId { get; set; }
        public string SkillsName { get; set; }
        public Nullable<byte> Derece { get; set; }
        public string Description { get; set; }
    }
}
