//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace portfolyo2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_services
    {
        public int ServiceID { get; set; }
        public string Description { get; set; }
        public string tittle { get; set; }
        public string Icon { get; set; }
        public string description2 { get; set; }
    }
}
