//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace portfolyo2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_slider
    {
        public int SlıderID { get; set; }
        public string NameSurname { get; set; }
        public string Description { get; set; }
        public string ImageURL { get; set; }
    }
}
